---
latitude: 40.68891
longitude: -73.98897
map_zoom: 12
name: NU Hotel Brooklyn
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 85 Smith St
  street2: ''
  state: New York
  city: Brooklyn
  country: United States
  zip_code: '11201'
_hotel_id: NUH877
_portal_id: required-but-empty
_root_path: https://qa5.ttaws.com/rt
